name: goban
description: Goban is an adaptive Go board for flutter. Fully customisable & easy to interface with your game logic.
version: 0.1.2
author: Umut Seven <umutseven92@gmail.com>
homepage: https://umutseven.com
repository: https://github.com/umutseven92/Goban

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.0.0+1
  tuple: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: